---
# tasks file for install_package_zabbix-agent
#
- block:
        #   - block:
  - name: Install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - sysstat
        - https://repo.zabbix.com/zabbix/5.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-agent-5.0.3-1.el{{ ansible_distribution_major_version }}.x86_64.rpm
       
  - name: Create directory for zabbix-scripts
    file: 
      path: /etc/zabbix/zabbix_scripts 
      mode: '0771' 
      owner: zabbix 
      group: zabbix 
      state: directory
  - name: Copy HDD_iostat.sh
    copy: 
      src: HDD_iostat.sh
      dest: /etc/zabbix/zabbix_scripts/
      owner: zabbix
      group: zabbix
      mode: '0755'

  - name: Add df and HDD_iosstat settings to a file
    blockinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      block: |
        UserParameter=HDD.iostat[*], /etc/zabbix/zabbix_scripts/HDD_iostat.sh "$1" "$2"

  - name: Enable zabbix-agent
    service: name=zabbix-agent state=started enabled=yes

  when: ansible_distribution == "CentOS"

